name: Secret
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            PASSWORD: ${{ secrets.PASSWORD}}
        steps:
            # ログ出力はマスクされる
            - run: echo "${PASSWORD}"
            # ログ出力はマスクされない
            - run: echo "${PASSWORD:0:1} ${PASSWORD#?}"